#!/usr/bin/env python3
"""Generate INDEX.md and refresh the stats block in README.md.

Local frontmatter supplies the canonical title/series/tags; dev.to's API supplies
the live URL and engagement numbers. The public endpoint needs no credentials.
Set DEVTO_API_KEY to additionally pull page-view counts, which are private.

Usage:
    python scripts/gen_index.py            # write INDEX.md and update README.md
    python scripts/gen_index.py --check    # exit 1 if the files are out of date
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict

import yaml

ARTICLES_DIR = "articles"
INDEX_FILE = "INDEX.md"
README_FILE = "README.md"
USERNAME = "kanywst"
API = "https://dev.to/api"
USER_AGENT = "devto-repo-index/1.0 (+https://github.com/kasir-barati/dev.to)"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
STATS_BLOCK_RE = re.compile(r"(<!-- stats:start -->)(.*?)(<!-- stats:end -->)", re.DOTALL)


def fetch(url, headers=None):
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, **(headers or {})})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def fetch_remote():
    """Return {id: {url, reactions, comments, views, published_at}}."""
    remote = {}
    page = 1
    while True:
        batch = fetch(f"{API}/articles?username={USERNAME}&per_page=1000&page={page}")
        if not batch:
            break
        for article in batch:
            remote[article["id"]] = {
                "url": article["url"],
                "reactions": article.get("public_reactions_count", 0),
                "comments": article.get("comments_count", 0),
                "reading_time": article.get("reading_time_minutes"),
                "published_at": (article.get("published_at") or "")[:10],
                "views": None,
            }
        if len(batch) < 1000:
            break
        page += 1

    key = os.environ.get("DEVTO_API_KEY")
    if key:
        try:
            page = 1
            while True:
                batch = fetch(f"{API}/articles/me/all?per_page=1000&page={page}", {"api-key": key})
                if not batch:
                    break
                for article in batch:
                    if article["id"] in remote:
                        remote[article["id"]]["views"] = article.get("page_views_count")
                if len(batch) < 1000:
                    break
                page += 1
        except urllib.error.HTTPError as exc:
            print(f"[!] Could not fetch private stats ({exc.code}); continuing without view counts.", file=sys.stderr)

    return remote


def load_articles():
    articles = []
    for path in sorted(glob.glob(os.path.join(ARTICLES_DIR, "*.md"))):
        with open(path, encoding="utf-8") as handle:
            match = FRONTMATTER_RE.match(handle.read())
        if not match:
            continue
        try:
            fm = yaml.safe_load(match.group(1))
        except yaml.YAMLError:
            continue
        if isinstance(fm, dict) and fm.get("title"):
            articles.append((path, fm))
    return articles


def escape(text):
    return str(text).replace("|", "\\|")


def row(path, fm, remote):
    info = remote.get(fm.get("id")) or {}
    title = escape(fm["title"])
    link = f"[{title}]({info['url']})" if info.get("url") else title
    tags = ", ".join(f"`{t}`" for t in (fm.get("tags") or []))
    if fm.get("published") is not True:
        state = "draft"
    elif info.get("url"):
        state = info.get("published_at") or "published"
    else:
        state = "pending"
    engagement = ""
    if info.get("url"):
        parts = [f"{info['reactions']}👍"]
        if info["comments"]:
            parts.append(f"{info['comments']}💬")
        if info.get("views"):
            parts.append(f"{info['views']} views")
        engagement = " · ".join(parts)
    source = f"[src](./{path})"
    return f"| {link} | {tags} | {state} | {engagement} | {source} |"


HEADER = "| Article | Tags | Published | Engagement | Source |\n| --- | --- | --- | --- | --- |"


def build_index(articles, remote):
    by_series = defaultdict(list)
    standalone = []
    for path, fm in articles:
        (by_series[str(fm["series"])] if fm.get("series") else standalone).append((path, fm))

    published = sum(1 for _p, fm in articles if fm.get("published") is True)
    lines = [
        "<!-- Generated by scripts/gen_index.py. Do not edit by hand. -->",
        "",
        "# Article index",
        "",
        f"{len(articles)} article(s) in this repository, {published} published to "
        f"[dev.to/{USERNAME}](https://dev.to/{USERNAME}), across {len(by_series)} series.",
        "",
        "## Series",
        "",
    ]

    for name in sorted(by_series, key=lambda n: (-len(by_series[n]), n.lower())):
        entries = sorted(by_series[name], key=lambda e: e[0])
        lines += [f"### {escape(name)} ({len(entries)})", "", HEADER]
        lines += [row(path, fm, remote) for path, fm in entries]
        lines.append("")

    if standalone:
        lines += ["## Standalone", "", HEADER]
        lines += [row(path, fm, remote) for path, fm in sorted(standalone, key=lambda e: e[0])]
        lines.append("")

    return "\n".join(lines)


def build_stats(articles, remote):
    live = [(fm["title"], remote[fm["id"]]) for _p, fm in articles if fm.get("id") in remote]
    reactions = sum(item["reactions"] for _t, item in live)
    comments = sum(item["comments"] for _t, item in live)
    drafts = sum(1 for _p, fm in articles if fm.get("published") is not True)
    top = max(live, key=lambda entry: entry[1]["reactions"], default=None)

    parts = [
        f"**{len(articles)}** articles ({drafts} unpublished)",
        f"**{len(live)}** live on dev.to",
        f"**{reactions}** reactions",
        f"**{comments}** comments",
    ]
    text = "\n\n" + " · ".join(parts) + "\n"
    if top:
        title, info = top
        text += f"\nMost reacted: [{escape(title)}]({info['url']}) ({info['reactions']} reactions)\n\n"
    return text


def write(path, content, check):
    current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if current == content:
        print(f"[-] {path} is up to date.")
        return False
    if check:
        print(f"[!] {path} is out of date; run `make index`.")
        return True
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"[+] Wrote {path}.")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="report drift instead of writing")
    args = parser.parse_args()

    articles = load_articles()
    if not articles:
        print("[!] No articles found.")
        return 1
    remote = fetch_remote()
    print(f"[-] {len(articles)} local article(s), {len(remote)} remote article(s).")

    stale = write(INDEX_FILE, build_index(articles, remote) , args.check)

    readme = open(README_FILE, encoding="utf-8").read()
    if STATS_BLOCK_RE.search(readme):
        updated = STATS_BLOCK_RE.sub(lambda m: m.group(1) + build_stats(articles, remote) + m.group(3), readme)
        stale = write(README_FILE, updated, args.check) or stale
    else:
        print(f"[!] {README_FILE} has no <!-- stats:start --> block; skipping.")

    return 1 if (stale and args.check) else 0


if __name__ == "__main__":
    sys.exit(main())
